name: flutter_inject0r
description: "A lightweight dependency injection library for Flutter & Jaspr"
version: 0.0.3
homepage: https://www.github.com/frederikstonge/inject0r
resolution: workspace

environment:
  sdk: ^3.13.3
  flutter: ^3.47.3

dependencies:
  flutter:
    sdk: flutter
  inject0r: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter