name: inject0r

packages:
  - packages/*
  - examples/*

# Can be runned using dart run melos run <script_name>
scripts:
  get:
    description: Get dependencies for all packages
    run: dart run melos exec flutter pub get