name: jaspr_inject0r_bloc
description: "A lightweight dependency injection library for Flutter & Jaspr"
version: 0.0.2
homepage: https://www.github.com/frederikstonge/inject0r
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  bloc: ^9.0.0
  jaspr: ^0.23.1
  jaspr_inject0r: ^0.0.2

dev_dependencies:
  jaspr_test: ^0.23.1
