name: flutter_inject0r_example
description: "A new Flutter project."
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^18.0.1
  inject0r: ^0.0.1
  inject0r_shared_example: ^1.0.0
  flutter_inject0r: ^0.0.1
  flutter_inject0r_bloc: ^0.0.1
  material_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true