name: inject0r
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.github.com/frederikstonge/inject0r

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.4"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
