name: Publish packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    strategy:
      matrix:
        package:
          - inject0r
          - flutter_inject0r
          - jaspr_inject0r
          - flutter_inject0r_bloc
          - jaspr_inject0r_bloc

    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/${{ matrix.package }}